# Generated by Django 3.0.4 on 2020-03-16 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='고객명')),
                ('course_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='코스지역명')),
                ('which_day', models.CharField(choices=[('MON', '월'), ('TUE', '화'), ('WED', '수'), ('THU', '목'), ('FRI', '금')], default='코스요일', max_length=10)),
                ('address', models.CharField(blank=True, max_length=254, null=True, verbose_name='고객주소')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='연락처')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
