# Generated by Django 3.0.4 on 2020-03-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='which_day',
        ),
    ]
