# Generated by Django 3.0.4 on 2020-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegitable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='야채 이름')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='주요 단위')),
                ('sub_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='보조 단위')),
                ('sub_unit2', models.CharField(blank=True, max_length=100, null=True, verbose_name='보조 단위2')),
            ],
        ),
    ]
