# Generated by Django 3.0.4 on 2020-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegitable',
            name='name',
        ),
        migrations.AddField(
            model_name='vegitable',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='야채 이름(영어)'),
        ),
        migrations.AddField(
            model_name='vegitable',
            name='name_ko',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='야채 이름(한글)'),
        ),
    ]
