# Generated by Django 3.0.4 on 2020-03-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0002_auto_20200316_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vegitable',
            new_name='Vegetable',
        ),
    ]
