# Generated by Django 3.0.4 on 2020-03-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vegetable', '0003_auto_20200316_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_date', models.DateField(blank=True, null=True)),
                ('quantity_ctn', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='CTN')),
                ('quantity_bag', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='BAG')),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='KG')),
                ('quantity_ea', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='EA')),
                ('memo', models.TextField(blank=True, max_length=512, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('vege_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetable.Vegetable')),
            ],
        ),
    ]
