# Generated by Django 3.0.4 on 2020-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='사업장 이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='사용자명'),
        ),
    ]
