# Generated by Django 3.0.4 on 2020-03-16 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vegetable', '0003_auto_20200316_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_day', models.CharField(choices=[('MON', '월'), ('TUE', '화'), ('WED', '수'), ('THU', '목'), ('FRI', '금')], default='코스요일', max_length=10)),
                ('order_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='주문량')),
                ('order_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='주문 단위')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vegetable_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetable.Vegetable')),
            ],
            options={
                'verbose_name': '주문',
            },
        ),
    ]
